version: '3.3'

services: 
  customer_profile_app:
    container_name: 'transactions-history-backend'
    build: 
      context: ../../
      dockerfile: ./deployments/local-docker/dev.dockerfile
    restart: unless-stopped
    environment:
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org,direct
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
      - ENV=debug
      - PORT=${PORT}
      - AWS_ACCESSKEYID=${AWS_ACCESSKEYID}
      - AWS_SECRETACCESSKEY=${AWS_SECRETACCESSKEY}
      - AWS_DEFAULTREGION=${AWS_DEFAULTREGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
      - EMAIL_SMTP_USERNAME=${EMAIL_SMTP_USERNAME}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_IAM_USERNAME=${EMAIL_IAM_USERNAME}
    volumes: 
      - ../../:/go/src/transactions-history
    networks:
      - stori-transactions-history-network
    ports:
      # gin proxy port
      - "3003:3030"

networks:
  stori-transactions-history-network:
    external: true
