# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Install dependencies
      run: go mod tidy

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -v -buildvcs=false -o ./build/main main.go

    - name: Zip build file
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: '.'
        path: './build/main'

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Send Zip to S3
      run: aws s3 cp release.zip s3://transaction-history-stori-deployments/release.zip

    - name: Deploy to AWS Lambda
      run: aws lambda update-function-code --function-name transaction-history-service --s3-bucket transaction-history-stori-deployments --s3-key release.zip
    
    - name: Update Lambda alias
      run: aws lambda update-alias --function-name transaction-history-service --name latest --function-version $LATEST
